blogs/urls.py
from django.urls import path
from . import views
from  django.contrib.auth.decorators import login_required

# public route
urlpatterns = [
	path('', views.post_list, name='post_list'),
	path('related', views.related, name='related'),
	path('category/<str:category>', views.post_list, name='post_list_c'),
	path('<int:pk>/', views.post_detail, name='post_detail'),
	path('<int:pk>/<str:choice>', views.likedis, name='likedis'),
	path('logout_view', views.logout_view, name='logout_view'),
	path('register_user', views.register_user, name='register_user'),
	path('login_user', views.login_user, name='login_user'),
	path('data', views.data, name='data'),
	path('analytics', views.analytics_page, name='analytics'),
]

# required login user
urlpatterns.extend([
	path('<int:pk>/delete', login_required(views.post_delete), name='post_delete'),
	path('new/', login_required(views.post_new), name='post_new'),
	path('<int:pk>/edit/', login_required(views.post_edit), name='post_edit'),

	])

# required login superuser
urlpatterns.extend([

	path('<int:pk>/delete', login_required(views.post_delete), name='post_delete'),

	])

mysite/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from blogs import views

urlpatterns = [
    path('admin/', admin.site.urls, name="admin"),
    path('blogs/', include('blogs.urls')),
]


if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),

        # For django versions before 2.0:
        # url(r'^__debug__/', include(debug_toolbar.urls)),

    ] + urlpatterns

blogs/models.py
from django.db import models
from django.conf import settings
from django.utils import timezone
from django.contrib.auth.models import AnonymousUser

# Create your models here.
class Post(models.Model):
	author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
	title = models.CharField(max_length=200)
	text = models.TextField()
	list_categories = (
		('G', 'Game'),
		('F', 'Film'),
		('M', 'Music'),
		('P', 'Politics'),
	)
	categories = models.CharField(max_length=1, choices=list_categories)
	created_date = models.DateTimeField(default=timezone.now)
	published_date = models.DateTimeField(blank=True, null=True)

	def publish(self):
		self.published_date = timezone.now()
		self.save()

	def __str__(self):
		return self.title

class Comment(models.Model):
	author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
	post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name="comments",)
	text = models.TextField()
	created_date = models.DateTimeField(default=timezone.now)
	published_date = models.DateTimeField(blank=True, null=True)

	def publish(self):
		self.published_date = timezone.now()
		self.save()

	def __str__(self):
		return self.text

class Analytics(models.Model):
	members = (
		('U', 'User'),
		('A', 'Admin'),
		('G', 'Guest'),
	)
	post = models.ForeignKey(Post, on_delete=models.CASCADE, related_name="analytics",)
	who_visit = models.CharField(max_length=1, choices=members)
	last_updated = models.DateTimeField(default=timezone.now)
	time_visited = models.FloatField(default=0)
	updated = models.IntegerField(default=0)
	last_visited =  models.DateTimeField(default=timezone.now)

	like = models.IntegerField(default=0)
	dislike = models.IntegerField(default=0)
	num_comment =  models.IntegerField(default=0)
	num_visited = models.IntegerField(default=0)

class Nationality(models.Model):
	name = models.CharField(max_length=50)

	def __str__(self):
		return self.name

class Person(models.Model):
	name = models.CharField(max_length=50)
	nationality = models.ForeignKey(Nationality, on_delete=models.CASCADE)

	def __str__(self):
		return self.name

blogs/forms.py
from django import forms
from django.contrib.auth.models import User

from .models import Post, Comment, Person

class PostForm(forms.ModelForm):

	class Meta:
		model = Post
		fields = ('title', 'text', 'categories', )

class CommentForm(forms.ModelForm):

	class Meta:
		model = Comment
		fields = ('text',)

class RegisterForm(forms.ModelForm):

	class Meta:
		model = User
		fields = ('username', 'email', 'password',)

class PersonForm(forms.ModelForm):

	class Meta:
		model = Person
		fields = ('name', 'nationality', )

class LoginForm(forms.Form):
	username = forms.CharField()
	password = forms.CharField()

blogs/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import logout, authenticate, login
from django.utils import timezone
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.models import User
from django.contrib.auth.decorators import user_passes_test
from django.http import HttpResponse
from django.core.cache.backends.base import DEFAULT_TIMEOUT
from django.views.decorators.cache import cache_page
from django.conf import settings
from django.core.cache import cache
from django.core.paginator import Paginator
from django.db.models import Avg, Max, Min, Sum, Count, Variance

from .models import Post, Comment, Analytics, Person, Nationality
from .forms import PostForm, CommentForm, RegisterForm, LoginForm, PersonForm

CACHE_TTL = getattr(settings, 'CACHE_TTL', DEFAULT_TIMEOUT)

# Create your views here.
def data(request):
    return HttpResponse("{'posts':posts}")

def related(request):
    person = Person.objects.select_related('nationality')
    return render(request, 'blogs/related.html', {'person':person})

def analytics_page(request, category=''):
    analytics = Analytics.objects.select_related('post')
    data = analytics.aggregate(
#                       total post
                        Count('post'),
#                       visitor
                        Sum('num_visited'), Min('num_visited'), 
                        Max('num_visited'), Variance('num_visited'), Avg('num_visited'),
#                       Like
                        Sum('like'), Min('like'), 
                        Max('like'), Variance('like'), Avg('like'),
#                       DisLike
                        Sum('dislike'), Min('dislike'), 
                        Max('dislike'), Variance('dislike'), Avg('dislike'),
#                       Comments
                        Sum('num_comment'), Min('num_comment'), 
                        Max('num_comment'), Variance('num_comment'), Avg('num_comment'))

    total = data.values()

    return render(request, 'blogs/analytics_page.html', {'analytics':analytics, 'total':total})

def post_list(request, category=''):
    # c = cache.get('posts')
    # if c == None:
    #     data = Post.objects.filter(published_date__lte=timezone.now()).order_by('-published_date')
    #     if data != None:
    #         cache.set('posts', data, CACHE_TTL)
    #         posts = cache.get('posts')
    #     else:
    #         posts = c
    # else:
    #     posts = c
    posts = Post.objects.select_related('author').filter(published_date__lte=timezone.now(),
             categories__contains=category).order_by('-published_date').annotate(Count('categories'))
    paginator = Paginator(posts, 3)
    page = request.GET.get('page')
    post = paginator.get_page(page)
    return render(request, 'blogs/post.html', {'posts':post, 'rpost':posts})

def post_detail(request, pk):
    post = get_object_or_404(Post, pk=pk)
    comments = Comment.objects.filter(published_date__lte=timezone.now(),
                                    post=post).order_by('-published_date')
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.post = post
            comment.author = request.user
            comment.published_date = timezone.now()
            comment.save()
            analytics = Analytics.objects.get(post=post)
            analytics.num_comment = analytics.num_comment + 1
            analytics.save()
            return redirect('post_detail', pk=post.pk)
    else:
        form = CommentForm()
    analytics = Analytics.objects.get(post=post)
    analytics.num_visited = analytics.num_visited + 1
    analytics.time_visited = analytics.time_visited + 75
    analytics.last_visited = timezone.now()
    analytics.save()

    return render(request, 'blogs/post.html', {'analytics': analytics, 'post': post, 'form': form, 'comments': comments, })


# @cache_page(CACHE_TTL)
def post_new(request):
    if request.method == "POST":
        form = PostForm(request.POST)
        analytics = Analytics()
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.published_date = timezone.now()
            post.save()
            analytics.post = post
            analytics.last_updated = timezone.now()
            analytics.save()
            return redirect('post_detail', pk=post.pk)
    else:
        form = PostForm()
    return render(request, 'blogs/post.html', {'form': form})

def likedis(request, choice, pk):
    post = Post.objects.get(pk=pk)
    analytics = Analytics.objects.get(post=post)
    if choice == 'l':
        analytics.like = analytics.like + 1
    else:
        analytics.dislike = analytics.dislike + 1

    analytics.save()
    return redirect('post_detail', pk=post.pk)

def post_edit(request, pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == "POST":
        form = PostForm(request.POST, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.published_date = timezone.now()
            post.save()
            return redirect('post_detail', pk=post.pk)
    else:
        form = PostForm(instance=post)
    return render(request, 'blogs/post.html', {'form': form})

@user_passes_test(lambda u: u.is_superuser)
def post_delete(request, pk):
    post = get_object_or_404(Post, pk=pk)
    post.delete()
    return redirect('post_list')

def logout_view(request):
    logout(request)
    return redirect('post_list')
    
def register_user(request):
    if request.method == "POST":
        form = RegisterForm(request.POST)
        if form.is_valid():
            username = request.POST['username']
            password = request.POST['password']
            email = request.POST['email']
            is_staf = "t"
            user = User.objects.create_user(username, email, password)
            user.save()
            return redirect('post_list')
    else:
        form = RegisterForm()
    return render(request, 'blogs/loginRegister.html', {'form': form})

def login_user(request):
    if request.method == "POST":
        form = LoginForm(request.POST)
        username = request.POST['username']
        password = request.POST['password']
        if form.is_valid():
            user = authenticate(request, username=username, password=password)
            print(user)
            if user is not None:
                login(request, user)
                return redirect('post_list')
    else:
        form = LoginForm()
    return render(request, 'blogs/loginRegister.html', {'form': form})

blogs/templates/blogs/analytics_page.html
{% extends 'blogs/base.html' %}

{% block content %}
    <div class="container">

        <center><h1>Analytics</h1></center>
        <br><br><br><hr>
            <div class="row justify-content-center">
                <div class="col-4">
                    <p> total blog :</p>
                    <hr>
                    {% with 'total min max variance average' as aggrqueries %}
                    {% with 'visitor like dislike comment' as data %}

                    {% for i in data.split %}
                        {% for a in aggrqueries.split %}
                            <p>{{ a }} {{ i }} :</p>
                            <hr>
                        {% endfor %}
                    {% endfor %}

                    {% endwith %}
                    {% endwith %}
                </div>
                <div class="col-4">
                    {% for item in total %}
                        <p>{{ item }}</p>
                        <hr>
                    {% endfor %}
                </div>
            </div>
    </div>

{% endblock %}

blogs/templates/blogs/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <title>Django Girls blog</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="stylesheet" href="{% static 'css/blogs.css' %}">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <title>Hello, world!</title>
  </head>
  <body>
    {% include 'blogs/navbar.html' %}

    <div id="app">
        {% block content %}
        {% endblock %}
    </div>

    <div class="footer">
      <center><i>This Is Footer</i></center>
    </div>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
  <script type="text/javascript" src="{% static 'js/blogs.js' %}"></script>
<style type="text/css">
.container{
    padding: 100px;
}
body{
  overflow-x: hidden;
}
 html {
  scroll-behavior: smooth;
}
</style>
</html>

blogs/templates/blogs/loginRegister.html
{% extends 'blogs/base.html' %}

{% block content %}
{% with url_name=request.resolver_match.url_name %}
    <div class="container">
    <div class="login">
        <form method="POST" class="post-form">{% csrf_token %}
            <div class="card text-center">
              <div class="card-header">
                <h3 class="card-title">
                    {% if url_name == 'register_user' %}
                        Register
                    {% else %}
                        Login
                    {% endif %}
                </h3>
              </div>
              <div class="card-body">
                {{ form.as_p }}
                <button type="submit" class="btn btn-primary">
                    {% if url_name == 'register_user' %}
                        Register
                    {% else %}
                        Login
                    {% endif %}
                </button>
              </div>
              <div class="card-footer text-muted">
                {% if url_name == 'register_user' %}
                    Already have an account ? <a href="{% url 'login_user' %}">Sign in »</a>
                {% else %}
                     New to This Web ? <a href="{% url 'register_user' %}">Sign up now »</a>
                {% endif %}
              </div>
            </div>
        </form>
    </div>
    </div>
{% endwith %}
{% endblock %}

blogs/templates/blogs/navbar.html
<nav class="fixed-top">
<nav class="navbar navbar-expand-lg navbar-light">
  <a class="navbar-brand" href="/">DjangoGirls</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <div class="mr-auto"></div>
    <ul class="navbar-nav">

      {% with url_name=request.resolver_match.url_name %}

        {% if user.is_authenticated %}
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            {{ user.username }}
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            {% if user.is_superuser %}
              <a class="dropdown-item" href="/admin">Admin Panel</a>
            {% endif %}
            <a class="dropdown-item" href="{% url 'logout_view' %}">LogOut</a>
          </div>
        </li>

        <li class="nav-item">
          <a class="nav-link" href="{% url 'post_new' %}">New</a>
        </li>
        {% else %}
          <a class="nav-link" href="{% url 'register_user' %}">Register</a>
          <a class="nav-link" href="{% url 'login_user' %}">Login</a>

        {% endif %}
          <a class="nav-link" href="{% url 'analytics' %}">Analytics</a>
          <a class="nav-link" href="{% url 'related' %}">Select Related</a>

      {% endwith %}
    </ul>
  </div>
</nav>

{% with url_name=request.resolver_match.url_name %}

<nav aria-label="breadcrumb">
  <ol class="breadcrumb ">
    {% if url_name == 'post_detail' %}
    <li class="breadcrumb-item"><a href="{% url 'post_list' %}">Home</a></li>
    <li class="breadcrumb-item"><a href="{% url 'post_list' %}">Detail</a></li>
    {% else %}
    <li class="breadcrumb-item"><a href="{% url 'post_list' %}">Home</a></li>
    {% endif %}
  </ol>
</nav>

{% endwith %}

</nav>

<style type="text/css">
  .breadcrumb{
    margin: 0;
    background-color: rgba(0, 0, 0, 0)
  }
  .breadcrumb li a{
    color: #ddd;
  }
</style>

blogs/templates/blogs/post.html
{% extends 'blogs/base.html' %}
{% load post_extras %}

{% block content %}
{% with url_name=request.resolver_match.url_name %}
    <div class="container">

<!-- post edit page -->
        {% if url_name == 'post_edit' or url_name == 'post_new' %}

            <h2>New post</h2>
            {% if user.is_authenticated %}
            <form method="POST" class="post-form">{% csrf_token %}
                {{ form.as_p }}
                <button type="submit" class="btn btn-primary">Save</button>
            </form>
            {% endif %}

<!-- post detail page -->
        {% elif url_name == 'post_detail' %}

            {% if user.is_authenticated %}
                <a class="btn btn-info" href="{% url 'post_edit' pk=post.pk %}">update</a>
            {% endif %}
            {% if user.is_superuser %}
            <a class="btn btn-danger" href="{% url 'post_delete' pk=post.pk %}">Delete</a>
            {% endif %}

            <h2>{{ post.title }}</h2>
            {% if post.published_date %}
                <div class="date">
                    <i>{{ post.published_date }}</i>
                </div>
            {% endif %}

            <p>{{ post.text|linebreaksbr }}</p>
            <div class="comment">
                {% if user.is_authenticated %}
                <a class="btn btn-primary" href="{% url 'likedis' pk=post.pk choice='l' %}">Like</a>
                <a class="btn btn-danger" href="{% url 'likedis' pk=post.pk choice='t' %}">DisLike</a>
                <br><br><br><hr>
                <p>Analystics</p>
                <p>num visited : {{ analytics.num_visited }}</p>
                <p>Last Update : {{ analytics.last_updated }}</p>
                <p>Time Visited : {{ analytics.time_visited }}</p>
                <p>Like : {{ analytics.like }}</p>
                <p>Dislike : {{ analytics.dislike }}</p>
                <hr><br><br><br>
                <form method="POST" class="post-form">{% csrf_token %}
                    {{ form.as_p }}
                    <button type="submit" class="btn btn-primary">Post</button>
                </form>
                {% else %}
                    <h5>You need to login. to use the comment section :(( </h5>
                {% endif %}
                <h4>Comments</h4>
                {% for comment in comments %}
                <div class="comment-body">
                    <div class="card">
                        <div class="card-body">
                        <h5 class="card-title">{{ comment.author }}</h5>
                        <i>{{ comment.created_date }}</i>
                        <hr>
                        <p class="card-text">{{ comment.text }}</p>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>

        {% else %}
<!-- post list page -->
        <h2>Post</h2>
        <hr>
        <p>Select Categories : </p>
        <a class="btn btn-warning" href="{% url 'post_list' %}">All</a>
        <a class="btn btn-warning" href="{% url 'post_list_c' category='G' %}">Game</a>
        <a class="btn btn-warning" href="{% url 'post_list_c' category='M' %}">Music</a>
        <a class="btn btn-warning" href="{% url 'post_list_c' category='F' %}">Film</a>
        <a class="btn btn-warning" href="{% url 'post_list_c' category='P' %}">Politics</a>
        <br>
        <hr>
        <br>
        {% for post in posts %}
        <div id="blog_list">
          <div class="card-body">
            <h5 class="card-title">{{ post | upper }}</h5>
            {% if post.published_date %}
            <div class="date">
                <i>{{ post.published_date }}</i>
            </div>
            {% endif %}
            <p>Author : {{ post.author.username }}</p>
            <p class="card-text">{{ post.text | post_list_body | linebreaks }}</p>
            <p>Number Category : {{ post.categories__count }}</p>
            <a href="{% url 'post_detail' pk=post.pk %}" class="btn btn-primary">Read</a>
            {% if user.is_authenticated %}
            <a class="btn btn-info" href="{% url 'post_edit' pk=post.pk %}">update</a>
            {% endif %}
            {% if user.is_superuser %}
            <a class="btn btn-danger" href="{% url 'post_delete' pk=post.pk %}">Delete</a>
            {% endif %}
            <p>Category : </p>
            <p>{{ post.get_categories_display }}</p>
          </div>
        </div>
        {% endfor %}

        <nav aria-label="Page navigation example">
          <ul class="pagination">
            {% if posts.has_previous %}
                <li class="page-item"><a class="page-link" href="?page={{ posts.previous_page_number }}">Previous</a></li>
            {% endif %}
            <li class="page-item"><a class="page-link" href="#">{{ posts.number }} of {{ posts.paginator.num_pages }}.</a></li>
            {% if posts.has_next %}
                <li class="page-item"><a class="page-link" href="?page={{ posts.next_page_number }}">Next</a></li>
            {% endif %}
          </ul>
        </nav>


        {% endif %}


    </div>

{% endwith %}
{% endblock %}

blogs/templates/blogs/related.html
{% extends 'blogs/base.html' %}

{% block content %}
    <div class="container">

        <center><h1>select related</h1></center>
        {% for p in person %}
            <p>{{ p.name }} : {{ p.nationality.name }} </p>
        {% endfor %}
    </div>

{% endblock %}